base: &BASE
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432

development:
  <<: *BASE
  database: rallyclock_development

test:
  <<: *BASE
  database: rallyclock_test

production:
  <<: *BASE
  database: rallyclock_production

